# Generated by Django 5.2 on 2025-05-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('preparing', 'Готовится'), ('delivering', 'Доставляется'), ('completed', 'Завершен')], default='Готовится', max_length=20),
        ),
    ]
